AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'

Metrics/MethodLength:
  Max: 15
