name: CI

on:
  push:
    branches: "*"

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1.31.0
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Generate lockfile
        run: bundle lock

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('Gemfile.lock') }}

      - name: Set up Tablature
        run: bin/setup

      - name: Run tests
        run: bundle exec rspec
